#!/bin/bash
mkdir -p /dev/cpuset
mount none /dev/cpuset -t cpuset -o nodev,noexec,nosuid

mkdir /acct
mount none -t cgroup /acct -o cpuacct,nodev,noexec,nosuid

BIND_MOUNT_PATH="/var/lib/lxc/android/rootfs" /usr/sbin/mount-android.sh
