#!/bin/bash -e

systemctl disable lxc
systemctl disable lxc-net

systemctl enable android-mount.service
systemctl enable var-lib-lxc-android-rootfs.mount
systemctl enable system.mount
systemctl enable config.mount
systemctl enable bind-vendor.service
systemctl enable wlan-module.service
systemctl enable lxc-android.service

exit 0